name: EOCV-Sim CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build jar & shadow jar with Gradle
      run: ./gradlew :EOCV-Sim:build shadowJar
    # Upload final fat jar as artifact.
    - uses: actions/upload-artifact@master
      with:
        path: '**/*'

  test_linux:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/download-artifact@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test with Gradle
      run: cd artifact
      run: ./gradlew test


  release-dev:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/dev'}}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jar
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: |
            *.jar
        if: github.event_name == 'push'

  release-stable:
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/master' }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jar
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
