name: GitHub Releasing

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build shadow jar with Gradle
      run: ./gradlew shadowJar -x test
    # Upload final fat jar as artifact.
    - uses: actions/upload-artifact@master
      with:
        name: jar
        path: 'EOCV-Sim/build/libs'

  release-dev:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/dev'}}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jar
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: |
            *.jar
        if: github.event_name == 'push'

  release-stable:
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/master' }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jar
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
